# Generated by Django 3.2.7 on 2021-11-17 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('treatment', models.CharField(choices=[('Basic dentist Survey: 100€', 'BASIC DENTIST SURVEY: 100€'), ('Teeth whitening Service: 300€', 'TEETH WHITENING SERVICE: 300€'), ('Ceramic crowns and fillings: 100€', 'CERAMIC CROWNS AND FILLINGS: 100€'), ('Remove crowns, bridges Service: 50€', 'REMOVE CROWNS, BRIDGES SERVICE: 50€'), ('Overlay teeth whitening: 170€', 'OVERLAY TEETH WHITENING: 170€'), ('Make Braces: 2400€', 'MAKE BRACES: 2400€'), ('Covering the recession of the gums: 400€', 'COVERING THE RECESSION OF THE GUMS: 400€'), ('Removal of tooth: 150€', 'REMOVAL OF TOOTH: 150€'), ('Removal of tartar: 50€', 'REMOVAL OF TARTAR: 50€')], default='Basic dentist survey: 100€', max_length=100)),
                ('datetime', models.DateField(blank=True, null=True)),
                ('information', models.TextField(blank=True)),
                ('sent_date', models.DateField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('edited', models.BooleanField(default=False)),
                ('accepted_date', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('first_name',)},
            },
        ),
    ]
