# Generated by Django 3.2.7 on 2021-11-18 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointment_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='edited',
        ),
    ]
