# Generated by Django 3.2.7 on 2021-11-18 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_remove_appointment_edited'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-sent_date']},
        ),
    ]
