# Generated by Django 3.2.7 on 2021-09-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_appointment_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='treatment',
            field=models.CharField(choices=[('Tartar removal: 50€', 'TARTAR REMOVAL: 50€'), ('Teeth whitening: 250€', 'TEETH WHITENING: 250€'), ('Tooth removal: 150€', 'TOOTH REMOVAL: 150€'), ('Braces: 2400€', 'BRACES: 2400€')], default='Tartar removal: 50€', max_length=30),
        ),
    ]
