# Generated by Django 3.2.7 on 2021-09-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_auto_20210929_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='treatment',
            field=models.CharField(choices=[('Basic survey: 100€', 'BASIC SURVEY: 100€'), ('Tartar removal: 50€', 'TARTAR REMOVAL: 50€'), ('Teeth whitening: 250€', 'TEETH WHITENING: 250€'), ('Tooth removal: 150€', 'TOOTH REMOVAL: 150€'), ('Braces: 2400€', 'BRACES: 2400€')], default='Basic survey: 100€', max_length=30),
        ),
    ]
