# Generated by Django 3.2.7 on 2021-11-01 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_auto_20211101_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='delete',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='edit',
        ),
    ]
