# Generated by Django 3.2.7 on 2021-11-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_auto_20211101_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
